name: tinder_cats
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  http: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.9.0
  get_it: ^7.6.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_icons:
  image_path: "assets/icon/app_icon.jpg"
  android: true
  ios: false
  min_sdk_android: 21